### PR TITLE
Ali Uncu/James Davenport/Matthew England submission of examples from Prove_Ineq tool (Kauers)

### PR DESCRIPTION
**Pull request by JamesHDavenport**
75 examples, in each of three formats depending on how rational functions are managed.  See detailed comments in each file.

### CODE REVIEW

**Comment by JamesHDavenport** [comment]
Now fixed by a rename

**Comment by mpreiner** [comment]
@JamesHDavenport some of the submitted benchmarks of the Uncu family have a wrong status: 
```
QF_NRA/20220314-Uncu/Rational_Function_Proof_Calls_With_Basic_Denominator_Simplifications/BDC_ProveIneq_Mitrinovic_4_29_2.smt2: unsat but got sat
QF_NRA/20220314-Uncu/Rational_Function_Proof_Calls_With_Basic_Denominator_Simplifications/BDC_ProveIneq_ISSAC05_KnoppSchur_b.smt2: sat but got unsat
QF_NRA/20220314-Uncu/Polynomial_Proof_Calls/ProveIneq_ISSAC05_SignPattern_5p_1nneg_4m_1w_p.smt2: unsat but got sat
QF_NRA/20220314-Uncu/Rational_Function_Proof_Calls_With_Basic_Denominator_Simplifications/BDC_ProveIneq_ISSAC05_AmerMathMonthly10347RHS.smt2: unsat but got sat
QF_NRA/20220314-Uncu/Rational_Function_Proof_Calls_With_Disjunctive_Denominator_Simplifications/DDC_ProveIneq_ISSAC05_KnoppSchur_b.smt2: sat but got unsat
QF_NRA/20220314-Uncu/Rational_Function_Proof_Calls_With_Disjunctive_Denominator_Simplifications/DDC_ProveIneq_ISSAC05_AmerMathMonthly10347RHS.smt2: unsat but got sat
```
Should I change the status of the benchmarks accordingly?

**Comment by JamesHDavenport** [comment]
Thanks for these.  I think we really need to look at these first.
James

**Comment by mpreiner** [comment]
FYI: We plan to do a new SMT-LIB release by May 20th. It'd be great if you could fix the benchmarks until then.

**Comment by JamesHDavenport** [comment]
I think your message has crossed with Ali's.

James Davenport
Hebron & Medlock Professor of Information Technology, University of Bath
National Teaching Fellow 2014;  DSc (honoris causa) UVT
Former Fulbright CyberSecurity Scholar (at New York University)
Former Vice-President and Academy Chair, British Computer Society


My workload obliges me to work, and send e-mails, outside working hours, but I don’t expect recipients to respond outside their working hours

________________________________

**Comment by akuncu** [comment]
Dear Mathias,

James forwarded me your email and I responded to that but I think my response got lost in transit. I have modified the files to the shape they were originally intended to be. I am attaching all six files in a zip here. I would highly appreciate if you can replace the 6 issues you noted with these files.

Best regards,
Ali

[Issues_Corrected.zip](https://github.com/SMT-LIB/benchmark-submission/files/8694060/Issues_Corrected.zip)

**Comment by mpreiner** [comment]
Thanks for the fixes. I'll add them.

**Pull request merged**
