### PR TITLE
Add benchmark from SPARK on proof of GNAT light runtime library

### PR DESCRIPTION
**Pull request by yannickmoy**
This benchmark was produced by the SPARK proof tool GNATprove.
All VCs should be provable (unsat) as they were generated from fully
proved SPARK code of the GNAT light runtime library (keeping only
those VCs which cannot be proved under 1 second). 
These VCs combine integer and bitwise non-linear arithmetic.
Each VC corresponds to a single property at a given program point in
the SPARK program. Symbol bv2nat originally used for CVC4/Z3 was
replaced by explicit functions for converting from BV to Int, as this is
not accepted in pure SMT-LIB as detected by dolmen.

### CODE REVIEW

**Comment by yannickmoy** [comment]
Is it ok to use bv2nat in the benchmark? It is rejected by dolmen, as per this discussion: https://github.com/Gbury/dolmen/issues/94

**Comment by yannickmoy** [comment]
As mentioned above, dolmen rejects some benchmarks because `bv2nat` is not recognized. However, it's accepted by SMT-solvers like CVC4 and Z3. Should I remove all benchmarks which use `bv2nat` (1221 out of 1422 benchmarks), or is there a way to please dolmen here?

**Comment by hansjoergschurr** [comment]
We are currently trying to clarify the situation of `bv2nat` with the SMT-LIB specification maintainers.

**Comment by yannickmoy** [comment]
I see this submission is still open, is there a problem with the checks? It seems they were not run on the latest version.

**Pull request merged**
